export enum ModelScales {
  ONETOTWELVE = "1:12",
  ONETOEIGHTEEN = "1:18",
  ONETOTWENTYFOUR = "1:24",
  ONETOTHIRTYTWO = "1:32",
  ONETOTHIRTYSIX = "1:36",
  ONETOFOURTYTHREE = "1:43",
  ONETOSIXTYFOUR = "1:64",
  ONETOSEVENTYSIX = "1:76",
  ONETOEIGHTYSEVEN = "1:87",
}
